name: Deploy to Server
on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: prod
    steps:
    
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup Java JDK
      uses: actions/setup-java@v4
      with:
        java-version: 21
        distribution: 'temurin'

    # 如果通过SSH部署
    # - name: Setup SSH
    #   uses: kielabokkie/ssh-key-and-known-hosts-action@v1.4.1
    #   with:
    #     ssh-private-key: ${{ secrets.PRIVATE_KEY }}
    #     ssh-host: ${{ secrets.SERVER_IP }}

    - name: Setup SSH Keys
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts

    - name: Build with Maven
      run: mvn clean package -DskipTests=true

    - name: Get JAR file name and timestamp
      id: jar_info
      run: |
        JAR_FILE=$(find target -type f -name "*.jar")
        TIMESTAMP=$(date +%Y%m%d%H%M%S)
        echo "::set-output name=jar_file::$JAR_FILE"
        echo "::set-output name=timestmap::$TIMESTAMP"

    - name: Copy to Server
      run: |
        cd target
        scp ${{ steps.jar_info.outputs.jar_file }}.jar ${{ secrets.USER_NAME }}@${{ secrets.SERVER_IP }}:~/learn-github-action/${{ steps.jar_info.outputs.jar_file }}-${{ steps.jar_info.outputs.timestamp }}.jar
