name: Deploy to Server
on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: prod
    steps:
    
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup Java JDK
      uses: actions/setup-java@v4
      with:
        java-version: 21
        distribution: 'temurin'

    - name: Setup SSH Keys
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts

    - name: Build with Maven
      run: mvn clean package -DskipTests=true

    - name: Get JAR base name and timestamp
      id: jar_info
      run: |
        JAR_FILE_WITH_SUFFIX=$(find target -type f -name "*.jar")
        JAR_BASE_NAME=$(basename "$JAR_FILE_WITH_SUFFIX" .jar)
        JAR_TIMESTAMP=$(date +%Y%m%d%H%M%S)
        echo "JAR_BASE_NAME=$JAR_BASE_NAME" >> $GITHUB_ENV
        echo "TIMESTAMP=$JAR_TIMESTAMP" >> $GITHUB_ENV

    - name: Copy to Server and Run
      run: |
        cd target
        scp ${{ env.JAR_BASE_NAME }}.jar ${{ secrets.USER_NAME }}@${{ secrets.SERVER_IP }}:~/learn-github-action/${{ env.JAR_BASE_NAME }}.jar
        ssh ${{ secrets.USER_NAME }}@${{ secrets.SERVER_IP }} '
          screen -S learn-github-action -X quit
          screen -dmS learn-github-action
          screen -S learn-github-action -X stuff "java -jar ~/learn-github-action/${{ env.JAR_BASE_NAME }}.jar$(printf \\r)"
        '
